Vocabulary size: 43405
Experiment dir: checkpoint/ours-jsw-attn+pe/20231026-180018
Vocabulary size: 43405
Maximum length: 15
Maximum length: 15
Maximum length: 15
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/run.py", line 226, in <module>
    main(args)
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/run.py", line 141, in main
    model = attnVAE(**kwargs)
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/models_tf/decomposed_vae.py", line 70, in __init__
    self.vae = VAE(**vae_params)
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/models_tf/vae.py", line 54, in __init__
    self.decoder = LSTMDecoder(
TypeError: __init__() missing 1 required positional argument: 'bow_size'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/reconstract.py", line 8, in <module>
    import config_attn as config
ModuleNotFoundError: No module named 'config_attn'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/reconstract.py", line 8, in <module>
    import config_attn as config
ModuleNotFoundError: No module named 'config_attn'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/evaluate.py", line 354, in <module>
    main(args)
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/evaluate.py", line 117, in main
    eval_data = MonoTextData(target_pth, True, vocab=vocab, b_vocab=b_vocab)
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/utils/text_utils.py", line 143, in __init__
    ) = self._read_corpus(fname, label, max_length, vocab, b_vocab, ft)
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/utils/text_utils.py", line 156, in _read_corpus
    with open(fname) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/ours-jsw-attn+pe/20231026-180018/reconstracted_results.txt'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/evaluate.py", line 354, in <module>
    main(args)
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/evaluate.py", line 117, in main
    eval_data = MonoTextData(target_pth, True, vocab=vocab, b_vocab=b_vocab)
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/utils/text_utils.py", line 143, in __init__
    ) = self._read_corpus(fname, label, max_length, vocab, b_vocab, ft)
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/utils/text_utils.py", line 156, in _read_corpus
    with open(fname) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/ours-jsw-attn+pe/20231026-180018/transfer_results.txt'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/recon_to_pos.py", line 222, in <module>
    main(args)
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/recon_to_pos.py", line 92, in main
    with open(path, "r") as fin, open(
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/ours-jsw-attn+pe/20231026-180018/transfer_results.txt'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/recon_to_pos.py", line 222, in <module>
    main(args)
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/recon_to_pos.py", line 92, in main
    with open(path, "r") as fin, open(
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/ours-jsw-attn+pe/20231026-180018/transfer_results.txt'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/evaluate.py", line 354, in <module>
    main(args)
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/evaluate.py", line 126, in main
    eval_data = MonoTextData(
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/utils/text_utils.py", line 143, in __init__
    ) = self._read_corpus(fname, label, max_length, vocab, b_vocab, ft)
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/utils/text_utils.py", line 156, in _read_corpus
    with open(fname) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/ours-jsw-attn+pe/20231026-180018/transfer_results0_1.txt'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/evaluate.py", line 354, in <module>
    main(args)
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/evaluate.py", line 119, in main
    eval_data = MonoTextData(
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/utils/text_utils.py", line 143, in __init__
    ) = self._read_corpus(fname, label, max_length, vocab, b_vocab, ft)
  File "/nas02/homes/yoshioka20-1000032/TG/CVAE-t-CWS/utils/text_utils.py", line 156, in _read_corpus
    with open(fname) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/ours-jsw-attn+pe/20231026-180018/transfer_results1_0.txt'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/reconstract.py", line 8, in <module>
    import config_attn as config
ModuleNotFoundError: No module named 'config_attn'
Traceback (most recent call last):
  File "/home/yoshioka20/nas02home/TG/CVAE-t-CWS/reconstract.py", line 8, in <module>
    import config_attn as config
ModuleNotFoundError: No module named 'config_attn'
